### ISSUE TITLE
Sizing Issue

### ISSUE THREAD

**Issue by djrobby** [JNKKKK/MoreToggles.css#1]
When I try to use the following code:
```html
<div class="mt-normal-juice">
  <input id="1" type="checkbox">
  <label for="1"></label>
</div>
```
the toggle appears to be sized a bit larger than needed...see below
![SS_20200408_50](https://user-images.githubusercontent.com/22199/78803655-3f71e580-798d-11ea-88ab-9a08a8e0189a.png)
FYI, I tried changing my base font-size to 13px as per your example and that didn't have any effect on its appearance. It just made the overall size smaller.

**Comment by JNKKKK** [comment]
Hi,

It looks like the width and height of `<div class="mt-normal-juice">` or `<label for="1"></label>` are overridden by other CSS rules you use in the context.

You can try
```html
<div class="mt-normal-juice" style="width:7em;height:3em;">
  <input id="1" type="checkbox">
  <label for="1" style="width:100%;height:100%;"></label>
</div>
```
If it's still not working, please create an example on [codepen.io](https://codepen.io/) to reproduce this issue. I'm very willing to help you collaboratively on [codepen.io](https://codepen.io/).

**Comment by djrobby** [comment]
Thank you for your prompt response. I think I've found my issue. I'm using TailwindCSS and one of the libs custom label tags was overriding this. All set for now. Apologize for the trouble.
