### ISSUE TITLE
Emoji Sliders don't move flush-right

### ISSUE THREAD

**Issue by r-i-c-h** [JNKKKK/MoreToggles.css#2]
Chrome 81 / Mac OS

Peeping https://jnkkkk.github.io/MoreToggles.css/allToggles.html, your "emoji" sliders will all move their icons flush to the left side, but when activated, the icons will only move about 2/3rds of the way to the right. 
<img width="1205" alt="Screen Shot 2020-05-27 at 5 07 28 PM" src="https://user-images.githubusercontent.com/19735136/83084012-96ff0a00-a03c-11ea-98e4-6989eb483ab5.png">

**Comment by Sojiro** [comment]
Reproducible for Safari 12.0.3 too

**Comment by Sojiro** [comment]
Reproducible for Safari 12.0.3 too

**Comment by Sojiro** [comment]
Reproducible for Safari 12.0.3 too

**Comment by Sojiro** [comment]
Reproducible for Safari 12.0.3 too

**Comment by varunsridharan** [comment]
Reproducible for Firefox 81.0.1 too
